endpoint: wss://rpc-shadow.crust.network/
mock-signature-host: true
block: ${env.CRUST_SHADOW_BLOCK_NUMBER}
db: ./crust.db.sqlite
runtime-log-level: 5

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000